# Generated by Django 5.2 on 2026-03-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_delete_user_schoolclass_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='student_courses', to='school.course'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='grade',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='student_courses', to='school.student'),
        ),
        migrations.AddConstraint(
            model_name='studentcourse',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course'),
        ),
    ]
