# Generated by Django 5.2.12 on 2026-03-29 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_delete_user_schoolclass_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='password',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='username',
        ),
    ]
