# Generated by Django 5.2.12 on 2026-03-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_schoolclass_password_and_more'),
        ('school', '0005_studentcourse_constraints'),
    ]

    operations = [
    ]
