# Generated by Django 5.2.12 on 2026-03-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_studenttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
