# Generated by Django 5.2.12 on 2026-03-30 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_student_password_alter_student_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolClass',
        ),
    ]
