-- ---------------------------------------------------------------------
-- ------------------------- Stored Procedures -------------------------
-- ---------------------------------------------------------------------

-- 1. Create a stored procedure that takes customer_id and 
-- returns a result set containing the full name, email, full address, and city of that customer.

DELIMITER /
create procedure get_customer_info(in c_id int)
begin
	select concat(c.first_name, ' ', c.last_name) as full_name, 
		c.email,
		concat(a.address, ' ', a.district, ' ', ci.city) as full_address, 
        ci.city
	from customer c join address a on c.address_id = a.address_id
    join city ci on a.city_id = ci.city_id
    where c.customer_id = c_id;
end /
DELIMITER ;

call get_customer_info(1);







-- 2. Create a stored procedure that takes a start_date and end_date 
-- and returns the total revenue generated by each store during that period.

DELIMITER /
create procedure get_total_revenue(in s_date date, in e_date date)
begin
	select st.store_id, sum(p.amount) as total_revenue
    from payment p
    join staff s on p.staff_id = s.staff_id
    join store st on s.store_id = st.store_id
    where p.payment_date between s_date and e_date
    group by st.store_id;
end /
DELIMITER ;

call get_total_revenue('2005-05-01', '2005-05-31');








-- 3. Create a stored procedure that takes a partial string (e.g., 'dark') and 
-- returns all films whose titles contain that string, along with their ratings.

DELIMITER /
create procedure get_films_title(in str varchar(20))
begin
	select ft.film_id, ft.title, f.rating
    from film f
    join film_text ft on f.film_id = ft.film_id
    where ft.title like concat('%', str, '%');
end /
DELIMITER ;

call get_films_title("dark");









-- 4. Create a stored procedure that takes customer_id and 
-- returns the name of the category (e.g., 'Action') that the customer rents most often.

DELIMITER //
CREATE PROCEDURE get_favorite_category(IN c_id INT)
BEGIN
    SELECT c.customer_id, c.first_name, cat.name AS category_name, COUNT(*) AS rental_count
    FROM customer c
    JOIN rental r ON c.customer_id = r.customer_id
    JOIN inventory i ON r.inventory_id = i.inventory_id
    JOIN film_category fc ON i.film_id = fc.film_id
    JOIN category cat ON fc.category_id = cat.category_id
    WHERE c.customer_id = c_id
    GROUP BY c.customer_id, c.first_name, cat.name
    ORDER BY rental_count DESC
    LIMIT 1;
END //
DELIMITER ;

call get_favorite_category(2);
















-- ---------------------------------------------------------------------
-- ------------------------------ Trigger ------------------------------
-- ---------------------------------------------------------------------

-- 1. Create a BEFORE UPDATE trigger on address table to set last_update = NOW() 
-- whenever a row is changed.

DELIMITER /

create trigger update_last_time
before update on address
for each row
begin
	set new.last_update = now();
end /

DELIMITER ;






 -- 2. Create a trigger to prevent an UPDATE to the staff table if the username is changed to 'admin'
 
DELIMITER /
create trigger prevent_update
before update on staff
for each row
begin
	if new.username = "admin" then
		signal sqlstate '45000'
        set message_text = "update is denied.";
	end if;
end /
DELIMITER ;








-- 3. Create a BEFORE INSERT trigger on the customer table to ensure that any email address 
-- entered contains both an @ and a . symbol.

DELIMITER /
create trigger customer_email_validation
before insert on customer
for each row
begin
	if new.email not REGEXP '^[^@]+@[^@]+\.[^@]{2,}$' then
		signal sqlstate '45000'
        set message_text = "wrong email formate.";
	end if;
end /
DELIMITER ;








-- 4. Create a table film_price_history. Create an AFTER UPDATE trigger on the film table 
-- that records the old price, new price, and change date whenever the rental_rate is modified

DELIMITER /
create trigger film_price_history
after update on film
for each row
begin
	if old.rental_rate <> new.rental_rate then
		insert into film_price_history(film_id, old_rental_rate, new_rental_rate, change_date)
        value (new.film_id, old.rental_rate, new.rental_rate, now());
    end if;
end /
DELIMITER ;